### ISSUE TITLE
Jenkins PR-merge job fails

### ISSUE THREAD

**Issue by BelfordZ** [etclabscore/jade-service-runner#43]
**Describe the bug**
Every PR is having checks fail because the jenkins build is borked.

**To Reproduce**
1. Change readme
2. Make a pr

**Expected behavior**
all green

**Screenshots**
![image](https://user-images.githubusercontent.com/1787231/59218339-e79ffd80-8b74-11e9-9178-5a74163d0d17.png)

**Comment by zcstarr** [comment]
Windows jenkins slave is out of space.
